//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnQLNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildDetail
    {
        public int IdChild { get; set; }
        public int IdDetail { get; set; }
        public string NameChild { get; set; }
        public Nullable<int> Hours { get; set; }
    
        public virtual DetailType1 DetailType1 { get; set; }
    }
}
