//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnQLNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailStatementLe
    {
        public int IdDtST { get; set; }
        public Nullable<int> IdSt { get; set; }
        public string IdTp { get; set; }
        public Nullable<int> Times { get; set; }
        public string Status { get; set; }
    
        public virtual TopicOfLecture TopicOfLecture { get; set; }
        public virtual Statement Statement { get; set; }
    }
}
