//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnQLNCKH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DHTDTTDNEntities1 : DbContext
    {
        public DHTDTTDNEntities1()
            : base("name=DHTDTTDNEntities12")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<ChildDetail> ChildDetails { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DetailStatementLe> DetailStatementLes { get; set; }
        public virtual DbSet<DetailType1> DetailType1 { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<Extension> Extensions { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<PointTable> PointTables { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<ProgressLe> ProgressLes { get; set; }
        public virtual DbSet<ProgressSt> ProgressSts { get; set; }
        public virtual DbSet<Statement> Statements { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TopicOfLecture> TopicOfLectures { get; set; }
        public virtual DbSet<TopicOfStudent> TopicOfStudents { get; set; }
        public virtual DbSet<Type> Types { get; set; }
    }
}
