//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnQLNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointTable
    {
        public int IdP { get; set; }
        public Nullable<int> IdAu { get; set; }
        public string IdTp { get; set; }
        public Nullable<double> Hours { get; set; }
        public Nullable<byte> Grade { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
